spring:

  #静态资源处理
  thymeleaf:
    cache: false
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/seckill?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123
    hikari:
      #连接池名
      pool-name: DateHikariCP
      #最小空闲连接数
      minimum-idle: 2
      #空闲连接存活最大时间, 默认600000(10分钟)
      idle-timeout: 180000
      #最大连接数
      maximum-pool-size: 10
      #自动提交
      auto-commit: true
      #最大存活时间 0表示永久 默认半小时
      max-lifetime: 180000
      #连接超时时间,默认30000(30秒)
      connection-timeout: 30000
      #测试连接是否可用
      connection-test-query: SELECT 1
  redis:
    host: 192.168.74.129
    port: 6379
    #第几个数据库
    database: 0
    connect-timeout: 10000ms
    lettuce:
      pool:
        max-active: 8
        max-wait: 10000ms
        max-idle: 200
        min-idle: 5
  rabbitmq:
    host: 192.168.74.129
    username: guest
    password: guest
    #虚拟主机
    virtual-host: /
    port: 5672
    listener:
      simple:
        #消费者最小数量
        concurrency: 10
        #消费者最大数量
        max-concurrency: 10
        #限制消费者每次只处理一条消息,处理完下一条
        prefetch: 1
        #启动时是否默认启动容器, 默认true
        auto-startup: true
        #被拒绝时重新进入队列
        default-requeue-rejected: true
    template:
      retry:
        #发布重试,默认false
        enabled: true
        #重试时间,默认1000ms
        initial-interval: 1000ms
        #重试最大次数 默认3次
        max-attempts: 3
        #重试最大间隔时间, 默认10000ms
        max-interval: 10000ms
        #重试的间隔乘数
        multiplier: 1
  web:
    resources:
      #启动默认静态资源处理
      add-mappings: true
      cache:
        cachecontrol:
          #缓存相应时间,单位秒
          max-age: 3600
      chain:
        #资源链启动缓存
        cache: true
        #启用资源链
        enabled: true
        #启用压缩资源
        compressed: true
        #启用h5应用缓存
        html-application-cache: true
      static-locations: claccpath:/static/


mybatis-plus:
  #配置Mapper.xml映射文件
  mapper-locations: classpath*:/mapper/*Mapper.xml
  #配置mybatis数据返回类型别名(默认别名是类名)
  type-aliases-package: com.example.seckilldemo.pojo

#mybatis的SQL打印日志
logging:
  level:
    com.example.seckilldemo.mapper: debug

